project_id="rdyjgnauilxswpzqiyne"

[functions.verify-email]
verify_jwt = false
[functions.get-visitor-ip]
enabled = true
verify_jwt = true
import_map = "./functions/get-visitor-ip/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-visitor-ip/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-visitor-ip/*.html" ]
